type User {
  id: ID!
  image: String
  username: String!
  bio: String
  email: String!
  followedByViewer: Boolean!

  articles(
    """Returns the first _n_ elements from the list."""
    first: Int

    """Returns the elements in the list that come after the specified cursor."""
    after: String

    """Returns the last _n_ elements from the list."""
    last: Int

    """
    Returns the elements in the list that come before the specified cursor.
    """
    before: String
  ): ArticleConnection!

  favoriteArticles(
    """Returns the first _n_ elements from the list."""
    first: Int

    """Returns the elements in the list that come after the specified cursor."""
    after: String

    """Returns the last _n_ elements from the list."""
    last: Int

    """
    Returns the elements in the list that come before the specified cursor.
    """
    before: String
  ): ArticleConnection!

  followers(
    """Returns the first _n_ elements from the list."""
    first: Int

    """Returns the elements in the list that come after the specified cursor."""
    after: String

    """Returns the last _n_ elements from the list."""
    last: Int

    """
    Returns the elements in the list that come before the specified cursor.
    """
    before: String
  ): FollowersConnection!
 
}

input CreateUserInput {
    username: String!
    email: String!
    password: String!
}

type CreateUserPayload {
    errors: [UserError!]!
    user: Viewer
}

input SignInUserInput {
    email: String!
    password: String!
}

type SignInUserPayload {
    errors: [UserError!]!
    token: String
    viewer: Viewer
}

input UnfollowUserInput {
    id: ID!
}

type UnfollowUserPayload {
    user: User
}

input UpdateUserInput {
  email: String!
  username: String!
  bio: String
  image: String
  password: String
}

type UpdateUserPayload {
  errors: [UserError!]!
  user: User
}

type UserEdge {
  cursor: String!
  node: User
}

type UserError {
    message: String!
    path: [String!]
}

type FollowersConnection {
    edges: [UserEdge]
    nodes: [User]
    pageInfo: PageInfo!
    totalCount: Int!
}

input FollowUserInput {
    id: ID!
    clientMutationId: String
}

type FollowUserPayload {
    clientMutationId: String
    user: User
}

type Query {
    user(username: String!): User
}

type Mutation {
    createUser(input: CreateUserInput!): CreateUserPayload
    followUser(input: FollowUserInput!): FollowUserPayload
    signInUser(input: SignInUserInput!): SignInUserPayload
    unfollowUser(input: UnfollowUserInput!): UnfollowUserPayload
    updateUser(input: UpdateUserInput!): UpdateUserPayload
}