version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: sudo npm install cross-env -g
            - run: npm install
            - run: cp ./.env.example ./.env
            - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test
