type Viewer {
  feed(
    """Returns the first _n_ elements from the list."""
    first: Int

    """Returns the elements in the list that come after the specified cursor."""
    after: String
  ): ArticleConnection!
  
  user: User!
}

type Query {
    viewer: Viewer
}